version: '3.8'

services:
  # 1. Cơ sở dữ liệu cho siêu thị
  db:
    image: postgres:15-alpine
    container_name: vdt_supermarket_db
    environment:
      POSTGRES_USER: vdt_admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: supermarket_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. Điều hướng cổng (API Gateway)
  nginx:
    image: nginx:alpine
    container_name: vdt_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db

  # 3. Redis (Dùng để lưu giỏ hàng tạm thời cho nhanh)
  cache:
    image: redis:6-alpine
    container_name: demi_redis

volumes:
  pgdata: