version: '3.8'

services:
  # 1. Cơ sở dữ liệu (Vẫn giữ để kết nối nội bộ hoặc backup)
  db:
    image: postgres:15-alpine
    container_name: vdt_supermarket_db
    environment:
      POSTGRES_USER: ${DB_USER:-supermarket_db_exvs_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-u0tGq1rZG5nb84Ek2siWlqzIDb9W8qO7}
      POSTGRES_DB: ${DB_NAME:-supermarket_db_exvs}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. Redis (Cache giỏ hàng)
  cache:
    image: redis:6-alpine
    container_name: demi_redis
    ports:
      - "6379:6379"

  # 3. Backend (Đóng gói Node.js)
  backend:
    build: ./backend-node
    container_name: vdt_backend
    env_file: .env
    depends_on:
      - db
      - cache
    # Khi chạy trong Docker, Backend sẽ gọi DB qua tên service 'db' hoặc 'host.docker.internal' cho Render

  # 4. Frontend (Đóng gói React/Vite)
  frontend:
    build: ./frontend-web
    container_name: vdt_frontend
    environment:
      - VITE_API_URL=http://localhost/api
    depends_on:
      - backend

  # 5. Nginx (Điều phối toàn bộ hệ thống)
  nginx:
    image: nginx:alpine
    container_name: vdt_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  pgdata: