server {
    listen 80;

    # Giao diện Web (Vite)
    location / {
        proxy_pass http://frontend:5173; # Chúng ta sẽ thêm service frontend sau
    }

    # API Backend (Node.js)
    location /api {
        proxy_pass http://backend:5000; # Chúng ta sẽ thêm service backend sau
    }
}