server {
    listen 80;
    server_name localhost;

    # 1. Điều hướng cho Backend (Đang chạy ở cổng 5000 máy Demi)
    location /api {
        proxy_pass http://host.docker.internal:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 2. Điều hướng cho Frontend (Đang chạy ở cổng 5173 máy Demi)
    location / {
        proxy_pass http://host.docker.internal:5173; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}